### ISSUE TITLE
compileflow跟Spring Boot怎么集成？会开发一个Starter吗？

### ISSUE THREAD

**Issue by SoftwareKing** [alibaba/compileflow#1]
compileflow跟Spring Boot怎么集成？会开发一个Starter吗？钉钉群号发一个或者二维码

**Comment by oldratlee** [comment]
> compileflow跟Spring Boot怎么集成？会开发一个Starter吗？

@SoftwareKing COOL idea 👍
可以 +1

> 钉钉群号发一个或者二维码

准备中

**Comment by yusu1210** [comment]
已提供Spring Boot Starter， https://github.com/alibaba/aliyun-spring-boot
