### ISSUE TITLE
当前只支持从resource 里面加载bpm文件，能否考虑通过db 后者配置中心等动态加载bpmn文件

### ISSUE THREAD

**Issue by lhfhit** [alibaba/compileflow#14]
当前只支持从resource 里面加载bpm文件，能否考虑通过db 后者配置中心等动态加载bpmn文件。

通过开放文件加载解析类，自行指定从配置中心或者其他地方获取xml bpm，然后动态编译成class.

**Comment by yusu1210** [comment]
可以考虑使用带content参数的api直接传入bpm文件内容，或者实现扩展点类FlowSourceLoader自定义加载更新策略
