### ISSUE TITLE
创建bpm文件后，绘制完流程图之后，流程图的连线位置会自动发生变化，可视性

### ISSUE THREAD

**Issue by pzandsz** [alibaba/compileflow#24]
绘制完时:
![image](https://user-images.githubusercontent.com/38871249/126091688-f30fb4d3-9535-4376-a975-3ec1fde028bb.png)

重新打开时:
![image](https://user-images.githubusercontent.com/38871249/126091719-98e96144-0443-4f91-8084-4ef83375d53b.png)

**Comment by xuan698400** [comment]
目前暂时还不支持线条的调整，不过最近支持了布局样式的设置调整，可以下载1.0.11版本的设计器，调整布局到自己合适的样式。后续会继续跟进看看，能不能调整线条的样式。https://github.com/compileflow/compileflow-designer-upgrade
