### ISSUE TITLE
2021.1版本的idea，编辑器调整的内容并不生效，也就是text里面根本没有改动，text里面调整了编辑器也没有同步

### ISSUE THREAD

**Issue by joakapp** [alibaba/compileflow#25]
2021.1版本的idea，编辑器调整的内容并不生效，也就是text里面根本没有改动，text里面调整了编辑器也没有同步

_Originally posted by @blake8816 in https://github.com/alibaba/compileflow/issues/9#issuecomment-880571368_

**Comment by xuan698400** [comment]
你系统是windows系统么，如果是的话，可能是编码问题，你可以设置下编码为UFT-8.

windows乱码问题：
在idea.vmoptions设置 -Dfile.encoding=UTF-8
