### ISSUE TITLE
这个目前支持端到端的网页形式吗？

### ISSUE THREAD

**Issue by zhanglijie123** [alibaba/compileflow#52]
> 这个问题反馈好慢啊

啥问题，可以提交一个iusses，贴的连接，我看到了会持续修复的。上面的报错？

_Originally posted by @xuan698400 in https://github.com/alibaba/compileflow/issues/9#issuecomment-1021990519_

**Comment by oldratlee** [comment]
这个是后端库，没有Web支持。

编辑功能参见 https://github.com/alibaba/compileflow-idea-designer
