### ISSUE TITLE
使用问题：我用JDK 15有问题（支持JDK 8以上的版本吗？）

### ISSUE THREAD

**Issue by lianlianyi** [alibaba/compileflow#8]

**Comment by oldratlee** [comment]
@lianlianyi 能更具体地说明你`JDK 15`的问题吗？
\# 我用`JDK 15/16` 运行与测试也是  OK的

**Comment by hongv** [comment]
升级17有这个问题：Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module
