### ISSUE TITLE
请问是否有官方的钉钉群，用于即时沟通？

### ISSUE THREAD

**Issue by bo961386926** [alibaba/compileflow#99]
请问这个开源的工作流引擎是否有官方的钉钉群？

**Comment by voff12** [comment]
邀请你加入钉钉群聊compileflow开源交流群，点击进入查看详情 https://qr.dingtalk.com/action/joingroup?code=v1,k1,WDav7ETpW/sKE4TwdOMq2lCge1d9yoW+11cMoFCtkHM=&_dt_no_comment=1&origin=11

**Comment by voff12** [comment]
![image](https://user-images.githubusercontent.com/1698192/194681407-a3cf37ea-a05f-4fa1-beb5-d575e789ef1a.png)
